# Hardware configuration for nfss (nix-based full ssd server)
# Same hardware as hs - generated by nixos-generate-config

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  # Boot configuration - detected kernel modules for this hardware
  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "usb_storage"
    "sd_mod"
    "sdhci_pci"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # ZFS filesystems are managed by disko configuration
  # No filesystem declarations needed here - disko handles all mounts

  # No swap devices configured
  swapDevices = [ ];

  # Networking hardware
  networking.useDHCP = lib.mkDefault true;

  # Hardware-specific settings
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  # CPU microcode updates
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Enable firmware updates
  hardware.enableRedistributableFirmware = lib.mkDefault true;
}
