[Interface]
# MacBook Air WireGuard Configuration
PrivateKey = eOmRh2Mrb9+xmbFtHtuOxlRM09ZLKOVWeoEQJk07bVo=
Address = 10.2.2.41/24
DNS = 1.1.1.1, 8.8.8.8

[Peer]
# VPS Server
PublicKey = 46QHjSzAas5g9Hll1SCEu9tbR5owCxXAy6wGOUoPwUM=
Endpoint = 91.98.84.215:51820
AllowedIPs = 10.2.2.0/24
PersistentKeepalive = 25
