# This file will be auto-generated by nixos-generate-config during installation
# It will contain the hardware scan results specific to your ThinkPad P14s Gen 2
# 
# DO NOT EDIT this file manually before installation!
# Run 'nixos-generate-config --show-hardware-config' on the target machine
# to generate the actual hardware configuration.

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  # This will be populated automatically during installation
  boot.initrd.availableKernelModules = [ ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  # Filesystem configuration will be added here by nixos-generate-config
  # based on your actual disk partitioning

  # Swap configuration (if applicable) will be added here

  # CPU and platform configuration will be detected and added here

  # The NixOS release version will be set here
  system.stateVersion = "24.05";
}