{ config, pkgs, lib, ... }:

{
  # Install termscp package
  home.packages = [ pkgs.termscp ];
  home.file.".config/termscp/config.toml".text = ''
    # termscp configuration file
    # Generated by Nix - see modules/termscp.nix for customization
    
    [user_interface]
    text_editor = "${config.home.homeDirectory}/.nix-profile/bin/nvim"
    default_protocol = "SFTP"
    show_hidden_files = true
    check_for_updates = true
    prompt_on_file_replace = true
    notifications = false
    notification_threshold = 536870912
   
    [remote]
    ssh_config = "${config.home.homeDirectory}/.ssh/config"

    [remote.ssh_keys]
  '';
}
