name: Evaluate Nix Configs
on: [push]

jobs:
  evaluate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: DeterminateSystems/nix-installer-action@main

      - name: Check config syntax
        run: |
          nix eval .#nixosConfigurations --apply 'builtins.mapAttrs (_: v: v.config.system.build.toplevel.drvPath)' --json > /dev/null
          nix eval .#darwinConfigurations --apply 'builtins.mapAttrs (_: v: v.config.system.build.toplevel.drvPath)' --json > /dev/null
          nix eval .#homeConfigurations --apply 'builtins.mapAttrs (_: v: v.activationPackage.drvPath)' --json > /dev/null

      - name: Send notification
        if: always()
        run: curl -s -d "Nix config evaluate ${{ job.status }}" https://ntfy.sh/yanlincs-homelab
